import React from "react";
export const metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
};
const contact = () => {
  return (
    <div>
      <h1>contect</h1>
    </div>
  );
};

export default contact;
